In [1]:
# Step 1: Import required libraries

import pandas as pd
import numpy as np

# Load the processed dataset
processed_path = r"C:\Users\akula\OneDrive\Desktop\DOCUMENTS\Seanergy_Preparation\Projects\Automated_Email_Classification\data\processed\spam_processed.csv"

df = pd.read_csv(processed_path)

print("Dataset loaded successfully!")
print("Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

Dataset loaded successfully!
Shape: (5169, 3)

Columns:
['target', 'message', 'transformed_text']


In [2]:
# Step 2: Check target labels

print("Target value counts:")
print(df["target"].value_counts())

print("\nTarget value types:")
print(df["target"].unique())


Target value counts:
target
ham     4516
spam     653
Name: count, dtype: int64

Target value types:
<StringArray>
['ham', 'spam']
Length: 2, dtype: str


In [3]:
# Step 3: Prepare input (X) and target (y)

# Input text
X = df["transformed_text"]

# Target label
y = df["target"].map({"ham": 0, "spam": 1})

print("X shape:", X.shape)
print("y shape:", y.shape)

print("\nFirst 5 input texts:")
print(X.head())

print("\nFirst 5 target values:")
print(y.head())

X shape: (5169,)
y shape: (5169,)

First 5 input texts:
0    go jurong point crazi avail bugi n great world...
1                                ok lar joke wif u oni
2    free entri 2 wkli comp win fa cup final tkt 21...
3                  u dun say earli hor u c alreadi say
4                 nah think goe usf live around though
Name: transformed_text, dtype: str

First 5 target values:
0    0
1    0
2    1
3    0
4    0
Name: target, dtype: int64


In [4]:
# Step 4: Split the dataset into training and testing sets

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training data:", X_train.shape)
print("Testing data:", X_test.shape)

print("\nTraining labels:")
print(y_train.value_counts())

print("\nTesting labels:")
print(y_test.value_counts())

Training data: (4135,)
Testing data: (1034,)

Training labels:
target
0    3613
1     522
Name: count, dtype: int64

Testing labels:
target
0    903
1    131
Name: count, dtype: int64


In [5]:
# Step 5: Convert text into numerical features using TF-IDF

from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer(
    max_features=5000,
    ngram_range=(1, 2),
    min_df=2,
    max_df=0.95
)


# Learn vocabulary only from training data
X_train_tfidf = tfidf.fit_transform(X_train)

# Transform testing data using the same vocabulary
X_test_tfidf = tfidf.transform(X_test)

print("TF-IDF vectorization completed successfully!")

print("\nTraining TF-IDF shape:", X_train_tfidf.shape)
print("Testing TF-IDF shape:", X_test_tfidf.shape)

TF-IDF vectorization completed successfully!

Training TF-IDF shape: (4135, 5000)
Testing TF-IDF shape: (1034, 5000)


In [6]:
# Step 6: Train Multinomial Naive Bayes

from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# Create the model
nb_model = MultinomialNB()

# Train the model
nb_model.fit(X_train_tfidf, y_train)

# Make predictions
y_pred_nb = nb_model.predict(X_test_tfidf)

# Calculate accuracy
nb_accuracy = accuracy_score(y_test, y_pred_nb)

print("Naive Bayes Model")
print("-----------------")
print("Accuracy:", nb_accuracy)

print("\nClassification Report:")
print(classification_report(
    y_test,
    y_pred_nb,
    target_names=["Ham", "Spam"]
))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_nb))

Naive Bayes Model
-----------------
Accuracy: 0.965183752417795

Classification Report:
              precision    recall  f1-score   support

         Ham       0.96      1.00      0.98       903
        Spam       0.99      0.73      0.84       131

    accuracy                           0.97      1034
   macro avg       0.98      0.87      0.91      1034
weighted avg       0.97      0.97      0.96      1034


Confusion Matrix:
[[902   1]
 [ 35  96]]


In [7]:
# Step 7: Train Logistic Regression

from sklearn.linear_model import LogisticRegression

# Create the model
lr_model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

# Train the model
lr_model.fit(X_train_tfidf, y_train)

# Make predictions
y_pred_lr = lr_model.predict(X_test_tfidf)

# Calculate accuracy
lr_accuracy = accuracy_score(y_test, y_pred_lr)

print("Logistic Regression Model")
print("-------------------------")
print("Accuracy:", lr_accuracy)

print("\nClassification Report:")
print(classification_report(
    y_test,
    y_pred_lr,
    target_names=["Ham", "Spam"]
))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_lr))

Logistic Regression Model
-------------------------
Accuracy: 0.9613152804642167

Classification Report:
              precision    recall  f1-score   support

         Ham       0.96      1.00      0.98       903
        Spam       1.00      0.69      0.82       131

    accuracy                           0.96      1034
   macro avg       0.98      0.85      0.90      1034
weighted avg       0.96      0.96      0.96      1034


Confusion Matrix:
[[903   0]
 [ 40  91]]


In [8]:
# Step 8: Train Support Vector Machine (SVM)

from sklearn.svm import LinearSVC

# Create the model
svm_model = LinearSVC(random_state=42)

# Train the model
svm_model.fit(X_train_tfidf, y_train)

# Make predictions
y_pred_svm = svm_model.predict(X_test_tfidf)

# Calculate accuracy
svm_accuracy = accuracy_score(y_test, y_pred_svm)

print("Support Vector Machine (SVM)")
print("----------------------------")
print("Accuracy:", svm_accuracy)

print("\nClassification Report:")
print(classification_report(
    y_test,
    y_pred_svm,
    target_names=["Ham", "Spam"]
))

print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred_svm))

Support Vector Machine (SVM)
----------------------------
Accuracy: 0.9777562862669246

Classification Report:
              precision    recall  f1-score   support

         Ham       0.98      0.99      0.99       903
        Spam       0.96      0.86      0.91       131

    accuracy                           0.98      1034
   macro avg       0.97      0.93      0.95      1034
weighted avg       0.98      0.98      0.98      1034


Confusion Matrix:
[[898   5]
 [ 18 113]]


In [9]:
# Step 9: Compare all models

from sklearn.metrics import precision_score, recall_score, f1_score

model_comparison = pd.DataFrame({
    "Model": [
        "Multinomial Naive Bayes",
        "Logistic Regression",
        "Linear SVM"
    ],
    "Accuracy": [
        accuracy_score(y_test, y_pred_nb),
        accuracy_score(y_test, y_pred_lr),
        accuracy_score(y_test, y_pred_svm)
    ],
    "Spam Precision": [
        precision_score(y_test, y_pred_nb),
        precision_score(y_test, y_pred_lr),
        precision_score(y_test, y_pred_svm)
    ],
    "Spam Recall": [
        recall_score(y_test, y_pred_nb),
        recall_score(y_test, y_pred_lr),
        recall_score(y_test, y_pred_svm)
    ],
    "Spam F1-Score": [
        f1_score(y_test, y_pred_nb),
        f1_score(y_test, y_pred_lr),
        f1_score(y_test, y_pred_svm)
    ]
})

print(model_comparison.round(4).to_string(index=False))

                  Model  Accuracy  Spam Precision  Spam Recall  Spam F1-Score
Multinomial Naive Bayes    0.9652          0.9897       0.7328         0.8421
    Logistic Regression    0.9613          1.0000       0.6947         0.8198
             Linear SVM    0.9778          0.9576       0.8626         0.9076


In [10]:
# Step 10: Save the trained model and TF-IDF vectorizer

import os
import joblib

# Create model directory
model_dir = r"C:\Users\akula\OneDrive\Desktop\DOCUMENTS\Seanergy_Preparation\Projects\Automated_Email_Classification\models"

os.makedirs(model_dir, exist_ok=True)

# Save the SVM model
svm_model_path = os.path.join(model_dir, "spam_classifier_svm.pkl")
joblib.dump(svm_model, svm_model_path)

# Save the TF-IDF vectorizer
tfidf_path = os.path.join(model_dir, "tfidf_vectorizer.pkl")
joblib.dump(tfidf, tfidf_path)

print("Model and vectorizer saved successfully!")
print("\nSVM model:")
print(svm_model_path)

print("\nTF-IDF vectorizer:")
print(tfidf_path)

Model and vectorizer saved successfully!

SVM model:
C:\Users\akula\OneDrive\Desktop\DOCUMENTS\Seanergy_Preparation\Projects\Automated_Email_Classification\models\spam_classifier_svm.pkl

TF-IDF vectorizer:
C:\Users\akula\OneDrive\Desktop\DOCUMENTS\Seanergy_Preparation\Projects\Automated_Email_Classification\models\tfidf_vectorizer.pkl


In [11]:
# Step 11: Load the saved model and TF-IDF vectorizer

import joblib

# Load SVM model
svm_model = joblib.load(svm_model_path)

# Load TF-IDF vectorizer
tfidf = joblib.load(tfidf_path)

print("SVM model loaded successfully!")
print("TF-IDF vectorizer loaded successfully!")

SVM model loaded successfully!
TF-IDF vectorizer loaded successfully!


In [12]:
# Step 12: Create a function to classify new emails

def predict_email(email_text):
    # Convert email text into TF-IDF features
    email_tfidf = tfidf.transform([email_text])
    
    # Predict the class
    prediction = svm_model.predict(email_tfidf)[0]
    
    return prediction

In [13]:
# Step 13: Test with a spam email

test_email = "Congratulations! You have won a free prize. Click here to claim your reward."

prediction = predict_email(test_email)

print("Email:", test_email)
print("Prediction:", prediction)

Email: Congratulations! You have won a free prize. Click here to claim your reward.
Prediction: 1


In [14]:
# Step 14: Test with a legitimate email

test_email = "Hi Priya, the project meeting is scheduled for tomorrow at 10 AM. Please bring the updated report."

prediction = predict_email(test_email)

print("Email:", test_email)
print("Prediction:", prediction)

Email: Hi Priya, the project meeting is scheduled for tomorrow at 10 AM. Please bring the updated report.
Prediction: 0


In [15]:
print("Target labels:")
print(y.unique())

Target labels:
[0 1]


In [16]:
print("Target value counts:")
print(y.value_counts())

Target value counts:
target
0    4516
1     653
Name: count, dtype: int64


In [17]:
# Step 15: Convert prediction into readable label

def classify_email(email_text):
    # Convert text into TF-IDF features
    email_tfidf = tfidf.transform([email_text])
    
    # Predict
    prediction = svm_model.predict(email_tfidf)[0]
    
    # Convert numeric prediction to readable label
    if prediction == 1:
        return "Spam"
    else:
        return "Ham"

In [18]:
# Step 16: Test the classification function

test_email = "Congratulations! You have won a free prize. Click here to claim your reward."

result = classify_email(test_email)

print("Email:", test_email)
print("Classification:", result)

Email: Congratulations! You have won a free prize. Click here to claim your reward.
Classification: Spam


In [19]:
# Step 17: Test with a legitimate message

test_email = "Hi Priya, the project meeting is scheduled for tomorrow at 10 AM. Please bring the updated report."

result = classify_email(test_email)

print("Email:", test_email)
print("Classification:", result)

Email: Hi Priya, the project meeting is scheduled for tomorrow at 10 AM. Please bring the updated report.
Classification: Ham


In [20]:
# Step 18: Test multiple new messages

test_emails = [
    "Congratulations! You have won a free lottery prize. Claim now!",
    "Can you send me the project report before today's meeting?",
    "URGENT! You have been selected for a cash reward. Click the link now.",
    "Your appointment is confirmed for tomorrow at 11 AM.",
    "You have won a free vacation. Call now to claim your prize."
]

for email in test_emails:
    result = classify_email(email)
    print("Email:", email)
    print("Classification:", result)
    print("-" * 80)

Email: Congratulations! You have won a free lottery prize. Claim now!
Classification: Spam
--------------------------------------------------------------------------------
Email: Can you send me the project report before today's meeting?
Classification: Ham
--------------------------------------------------------------------------------
Email: URGENT! You have been selected for a cash reward. Click the link now.
Classification: Spam
--------------------------------------------------------------------------------
Email: Your appointment is confirmed for tomorrow at 11 AM.
Classification: Ham
--------------------------------------------------------------------------------
Email: You have won a free vacation. Call now to claim your prize.
Classification: Spam
--------------------------------------------------------------------------------


In [21]:
# Step 19: Verify saved model files

print("Checking saved files...\n")

print("SVM model exists:", os.path.exists(svm_model_path))
print("TF-IDF vectorizer exists:", os.path.exists(tfidf_path))

print("\nModel directory:")
print(model_dir)

print("\nFiles in model directory:")
print(os.listdir(model_dir))

Checking saved files...

SVM model exists: True
TF-IDF vectorizer exists: True

Model directory:
C:\Users\akula\OneDrive\Desktop\DOCUMENTS\Seanergy_Preparation\Projects\Automated_Email_Classification\models

Files in model directory:
['spam_classifier_svm.pkl', 'tfidf_vectorizer.pkl']
